# Generated by Django 3.2.12 on 2023-01-05 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pict',
            name='name',
        ),
        migrations.AddField(
            model_name='pict',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
